# .github/workflows/backend.yml

name: CI Backend - Python/FastAPI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'backend/**' # Solo se ejecuta si hay cambios en la carpeta backend
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"] # Prueba en múltiples versiones de Python

    steps:
    - name: 1. Clonar el repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: 3. Instalar dependencias
      run: |
        cd backend # Navega a la carpeta del backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # --- DESCOMENTA ESTA SECCIÓN SI TIENES PRUEBAS CON PYTEST ---
    # - name: 4. Ejecutar pruebas con Pytest
    #   run: |
    #     cd backend
    #     pytest