name: CI - FastAPI + React

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Backend - FastAPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (FastAPI)
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint FastAPI code
        run: |
          cd backend
          python -m compileall .

  build-frontend:
    name: Frontend - React
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (React)
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build
